# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c52e4068f68d49a2c3dc1a15df774a0b158ab9a462062f327941e3fea5f917c774875587d15da033e8a8006bc4fd5f813804f6d639e5f1a7b1c5f2fd61ae623

test:
  secret_key_base: 4f8f1abcf14eccdf1544e19b80a2e2f7b1ed7a8d26d861823235e9b0844f7199975bdc86ecbe60f225a00d95faf96e8909267f870f0e07689595dc8f1a64a12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
